### ISSUE TITLE
typo on readme

### ISSUE THREAD

**Issue by jeremymiller** [AllenInstitute/scrattch.vis#25]
On the main readme tutorial `anno <- anno[anno$cluster_id > 0,]` should say `anno <- anno[anno$primary_type_id > 0,]`.

**Comment by hypercompetent** [comment]
I've added this fix to the repo:
https://github.com/AllenInstitute/scrattch.vis/commit/96710c395cf3bf362a0de119b4024c41121e4af6

Thanks, @jeremymiller !
