### ISSUE TITLE
Build and install fails using Rstudio Build 1379 (f1ac3452) on Windows 10

### ISSUE THREAD

**Issue by dpshepherd** [AllenInstitute/scrattch.vis#26]
Hello,

I am attempting to install scrattch.vis in Rstudio for use in another vignette. I am using R 3.6 with RStudio Build 1379 (f1ac3452) on a Windows 10 64-bit machine. 

Devtools works fine and I can install packages from other GitHub repositories.

The error messages I receive is:
```
* installing *source* package 'scrattch.vis' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Note: possible error in 'theme(plot.margin = unit(c(rep(0, ': formal argument "axis.ticks.x" matched by multiple actual arguments 
** help
Error : (converted from warning) C:/Users/dpshe/AppData/Local/Temp/RtmpKQzg5F/Rbuild9b464bf76ca/scrattch.vis/man/scrattch.vis-package.Rd:26: All text must be in a section
ERROR: installing Rd objects failed for package 'scrattch.vis'
* removing 'C:/Users/dpshe/Documents/R/win-library/3.6/scrattch.vis'
```

Any suggestions on how to get around this issue?

Thanks,
Doug

**Comment by hypercompetent** [comment]
Hi Doug,

Thanks for letting me know about this problem. I've made some updates to the package to fix this error. Please give it a shot, and let me know if you hit any other issues.

Cheers,
-Lucas

**Comment by dpshepherd** [comment]
Works now, thanks!
